"""
Common files and folders shared across project templates.
This is the default file structure extracted from cli.py.
"""

COMMON_FILES = [
    ".github/workflows/.gitkeep",
    ".github/workflows/ci-cd.yml",
    ".github/workflows/deploy.yml",
    "data/raw/",
    "data/processed/",
    "data/source.md",
    "docs/architecture.md",
    "docs/setup.md",
    "docs/api.md",
    "docs/requirements/prd.md",
    "docs/requirements/trd.md",
    "docs/decisions/decision.md",
    "src/__init__.py",
    "src/core/__init__.py",
    "src/api/__init__.py",
    "src/features/__init__.py",
    "src/components/__init__.py",
    "src/utils/__init__.py",
    "src/config/__init__.py",
    "src/config/configuration.py",
    "src/pipeline/__init__.py",
    "src/entity/__init__.py",
    "src/constants/__init__.py",
    "src/cache/__init__.py",
    "research/",
    "templates/",
    "logs/",
    "config/config.yaml",
    "config/config.py",
    "dvc.yaml",
    "params.yaml",
    "requirements.txt",
    "setup.py",
    ".gitignore",
    "README.md",
    ".env",
    ".env.example",
]
